name: Screenshot Automation
on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  screenshot:
    runs-on: ubuntu-latest  # Runs on free GitHub servers

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install playwright
        playwright install chromium

    - name: Run screenshot script
      run: |
        python3 screenshotter.py list --file urls.txt --output screenshots --delay 1

    - name: List files (for debugging)
      run: |
        ls -la screenshots/  # This step ensures files are being saved to the correct directory.

    - name: Upload screenshots
      uses: actions/upload-artifact@v4
      with:
        name: screenshots  # Name of the artifact
        path: screenshots/  # Path to the directory you want to upload
        compression-level: 6  # Adjust compression level for faster uploads (1-9, 6 is default)
        include-hidden-files: true  # Include hidden files (e.g., .gitignore)
        overwrite: true  # Allow overwriting of existing artifacts
